services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - backend

volumes:
  caddy_data:
